

#pragma once
#include <coretypes/common.h>

BEGIN_NAMESPACE_CQDAQ

#define CQDAQ_LOG_LEVEL_TRACE 0
#define CQDAQ_LOG_LEVEL_DEBUG 1
#define CQDAQ_LOG_LEVEL_INFO 2
#define CQDAQ_LOG_LEVEL_WARN 3
#define CQDAQ_LOG_LEVEL_ERROR 4
#define CQDAQ_LOG_LEVEL_CRITICAL 5
#define CQDAQ_LOG_LEVEL_OFF 6
#define CQDAQ_LOG_LEVEL_DEFAULT 7

END_NAMESPACE_CQDAQ
