
#pragma once
#include <coretypes/errors.h>

/*!
 * @ingroup cqdaq_errors_group
 * @addtogroup cqdaq_errors_macros Error Code Macros
 * @{
 */

#define CQDAQ_ERRTYPE_MODULE_MANAGER 0x03u

#define CQDAQ_ERR_MODULE_MANAGER_UNKNOWN           CQDAQ_ERROR_CODE(CQDAQ_ERRTYPE_MODULE_MANAGER, 0x0000u)
#define CQDAQ_ERR_MODULE_LOAD_FAILED               CQDAQ_ERROR_CODE(CQDAQ_ERRTYPE_MODULE_MANAGER, 0x0001u)
#define CQDAQ_ERR_MODULE_NO_ENTRY_POINT            CQDAQ_ERROR_CODE(CQDAQ_ERRTYPE_MODULE_MANAGER, 0x0002u)
#define CQDAQ_ERR_MODULE_ENTRY_POINT_FAILED        CQDAQ_ERROR_CODE(CQDAQ_ERRTYPE_MODULE_MANAGER, 0x0003u)
#define CQDAQ_ERR_MODULE_INCOMPATIBLE_DEPENDENCIES CQDAQ_ERROR_CODE(CQDAQ_ERRTYPE_MODULE_MANAGER, 0x0004u)

/*!
 * @}
 */
