//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CppGenerator v5.0.0) on 20.07.2024 00:55:27.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma once
#include <coretypes/coretypes.h>
#include "cqdaq/signal_private.h"
#include <coretypes/objectptr.h>




BEGIN_NAMESPACE_CQDAQ


class SignalPrivatePtr;



END_NAMESPACE_CQDAQ

BEGIN_NAMESPACE_CQDAQ

template <>
struct InterfaceToSmartPtr<daq::ISignalPrivate>
{
    using SmartPtr = daq::SignalPrivatePtr;
};


END_NAMESPACE_CQDAQ

BEGIN_NAMESPACE_CQDAQ



/*!
 * @ingroup cqdaq_signals
 * @addtogroup cqdaq_signal Signal
 * @{

 */


/*!
 * @brief Internal functions used by cqDAQ core. This interface should never be used in
 * client SDK or module code.

 */

class SignalPrivatePtr : public daq::ObjectPtr<ISignalPrivate>
{
public:
    using daq::ObjectPtr<ISignalPrivate>::ObjectPtr;
    //using daq::ObjectPtr<ISignalPrivate>::operator=;



    SignalPrivatePtr()
        : daq::ObjectPtr<ISignalPrivate>()

    {
    }

    SignalPrivatePtr(daq::ObjectPtr<ISignalPrivate>&& ptr)
        : daq::ObjectPtr<ISignalPrivate>(std::move(ptr))

    {
    }

    SignalPrivatePtr(const daq::ObjectPtr<ISignalPrivate>& ptr)
        : daq::ObjectPtr<ISignalPrivate>(ptr)

    {
    }

    SignalPrivatePtr(const SignalPrivatePtr& other)
        : daq::ObjectPtr<ISignalPrivate>(other)

    {
    }

    SignalPrivatePtr(SignalPrivatePtr&& other) noexcept
        : daq::ObjectPtr<ISignalPrivate>(std::move(other))

    {
    }
    
    SignalPrivatePtr& operator=(const SignalPrivatePtr& other)
    {
        if (this == &other)
            return *this;

        daq::ObjectPtr<ISignalPrivate>::operator =(other);


        return *this;
    }

    SignalPrivatePtr& operator=(SignalPrivatePtr&& other) noexcept
    {
        if (this == std::addressof(other))
        {
            return *this;
        }


        daq::ObjectPtr<ISignalPrivate>::operator =(std::move(other));

        return *this;
    }


    /*!
     * @brief Sets the domain signal to null without notifying the domain signal

     */
    void clearDomainSignalWithoutNotification() const
    {
        if (this->object == nullptr)
            throw daq::InvalidParameterException();

        auto errCode = this->object->clearDomainSignalWithoutNotification();
        daq::checkErrorInfo(errCode);
    }


    /*!
     * @brief Enable or disable keeping last data packet which is using by Signal method `getLastValue` 

     * @param enabled Option for enabling method getLastValue
     */
    void enableKeepLastValue(daq::Bool enabled) const
    {
        if (this->object == nullptr)
            throw daq::InvalidParameterException();

        auto errCode = this->object->enableKeepLastValue(enabled);
        daq::checkErrorInfo(errCode);
    }

#if __has_include(<cqdaq/signal_private_ptr.custom.h>)
    #include <cqdaq/signal_private_ptr.custom.h>
#endif
};

/*!
 * @}
 */


END_NAMESPACE_CQDAQ
