//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CppGenerator v5.0.0) on 20.07.2024 00:55:07.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma once
#include <coretypes/coretypes.h>
#include "coreobjects/unit.h"
#include <coretypes/objectptr.h>
#include <coretypes/string_ptr.h>




BEGIN_NAMESPACE_CQDAQ


class UnitPtr;



END_NAMESPACE_CQDAQ

BEGIN_NAMESPACE_CQDAQ

template <>
struct InterfaceToSmartPtr<daq::IUnit>
{
    using SmartPtr = daq::UnitPtr;
};


END_NAMESPACE_CQDAQ

BEGIN_NAMESPACE_CQDAQ



/*!
 * @ingroup cqdaq_data_descriptor
 * @addtogroup coreobjects_unit Unit
 * @{

 */


/*!
 * @brief Describes a measurement unit with IDs as defined in
 * <a href="https://unece.org/trade/cefact/UNLOCODE-Download">Codes for Units of Measurement used in International Trade</a>.

 * Unit objects implement the Struct methods internally and are Core type `ctStruct`.
 * @subsection unit_components Unit components
 * - ID: The unit ID as defined in <a href="https://unece.org/trade/cefact/UNLOCODE-Download">Codes for Units of Measurement used in International Trade</a>.
 *   Should be set to -1 if the unit ID is not available.
 * - Symbol: The symbol of the unit, i.e. "m/s". It is mandatory and must be set before the Unit object is frozen.
 * - Name: The full name of the unit, i.e. "meters per second". The unit's name is optional.
 * - Quantity: The quantity represented by the unit, i.e. "Velocity". The unit's quantity is optional.
 */

class UnitPtr : public daq::ObjectPtr<IUnit>
{
public:
    using daq::ObjectPtr<IUnit>::ObjectPtr;
    //using daq::ObjectPtr<IUnit>::operator=;



    UnitPtr()
        : daq::ObjectPtr<IUnit>()

    {
    }

    UnitPtr(daq::ObjectPtr<IUnit>&& ptr)
        : daq::ObjectPtr<IUnit>(std::move(ptr))

    {
    }

    UnitPtr(const daq::ObjectPtr<IUnit>& ptr)
        : daq::ObjectPtr<IUnit>(ptr)

    {
    }

    UnitPtr(const UnitPtr& other)
        : daq::ObjectPtr<IUnit>(other)

    {
    }

    UnitPtr(UnitPtr&& other) noexcept
        : daq::ObjectPtr<IUnit>(std::move(other))

    {
    }
    
    UnitPtr& operator=(const UnitPtr& other)
    {
        if (this == &other)
            return *this;

        daq::ObjectPtr<IUnit>::operator =(other);


        return *this;
    }

    UnitPtr& operator=(UnitPtr&& other) noexcept
    {
        if (this == std::addressof(other))
        {
            return *this;
        }


        daq::ObjectPtr<IUnit>::operator =(std::move(other));

        return *this;
    }


    /*!
     * @brief Gets the unit ID as defined in <a href="https://unece.org/trade/cefact/UNLOCODE-Download">Codes for Units of Measurement used in International Trade</a>.

     * @returns The unit ID.
     * Returns -1 if the unit id is not available.
     */
    daq::Int getId() const
    {
        if (this->object == nullptr)
            throw daq::InvalidParameterException();

        daq::Int id;
        auto errCode = this->object->getId(&id);
        daq::checkErrorInfo(errCode);

        return id;
    }


    /*!
     * @brief Gets the symbol of the unit, i.e. "m/s". 

     * @returns The unit's symbol.
     */
    daq::StringPtr getSymbol() const
    {
        if (this->object == nullptr)
            throw daq::InvalidParameterException();

        daq::StringPtr symbol;
        auto errCode = this->object->getSymbol(&symbol);
        daq::checkErrorInfo(errCode);

        return symbol;
    }


    /*!
     * @brief Gets the full name of the unit, i.e. "meters per second".

     * @returns The unit's full name.
     * `nullptr` if not set.
     */
    daq::StringPtr getName() const
    {
        if (this->object == nullptr)
            throw daq::InvalidParameterException();

        daq::StringPtr name;
        auto errCode = this->object->getName(&name);
        daq::checkErrorInfo(errCode);

        return name;
    }


    /*!
     * @brief Gets the quantity represented by the unit, i.e. "Velocity" 

     * @returns The unit's quantity.
     * `nullptr` if not set.
     */
    daq::StringPtr getQuantity() const
    {
        if (this->object == nullptr)
            throw daq::InvalidParameterException();

        daq::StringPtr quantity;
        auto errCode = this->object->getQuantity(&quantity);
        daq::checkErrorInfo(errCode);

        return quantity;
    }

#if __has_include(<coreobjects/unit_ptr.custom.h>)
    #include <coreobjects/unit_ptr.custom.h>
#endif
};

/*!
 * @}
 */


/*!
 * @brief Creates a Unit with Builder

 * @param builder Unit Builder
 */


END_NAMESPACE_CQDAQ
